sudo: false
dist: trusty
language: erlang
install: 'true'
before_script:
- wget https://s3.amazonaws.com/rebar3/rebar3
- wget https://github.com/rebar/rebar/wiki/rebar
- chmod +x rebar3
- chmod +x rebar
env: PATH=$PATH:.
cache:
  directories:
  - $HOME/.cache/rebar3/
otp_release:
- 21.3
- 22.3
script: "./bin/checks.sh && ./rebar3 as test coveralls send"
